language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: Hxse7noWGlXYE0EXEszH3YUNdFK8aMbMUqOu+ypmeG16kq0fCPgOMEe/QEiJLzV5WbZGFFuYiu13pmIQPjTJLG2eA+USWDXq9dLG3GufzCSBzlYqODldZgapBswT0JPuTHASPR2Ts6rC91DVs7zuCxZlb/OdxzDN5+1CorMVAWo=
  - secure: WzSuoxnXqDR7v1hEBBWO/1RQ1NypyvlrwUuyuxdMKELtYqPpel+akf4IK1nzOs5OOP3zXCy8efkEVT6K+G2eJc9IMzt33W1O7N2BMdfNWq632/kFwk63ObDjZYc056gT5a/wYBmaOgdvb4KP5uZ65nJN3oQyQM2JE6VKR3diKig=
